name: ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: 126031290970.dkr.ecr.us-east-2.amazonaws.com/test
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and tag docker image
        run: docker build . -t 126031290970.dkr.ecr.us-east-2.amazonaws.com/test --build-arg DATABASE_URL="postgresql://user:password@host:port/db?sslmode=require&pgbouncer=true" --build-arg SESSION_SECRET_KEY="yoursupersecretsessionkey"
      - name: Push to ECR
        run: docker push  126031290970.dkr.ecr.us-east-2.amazonaws.com/test
        
        
