name: ci

on:
  push:
    branches: [main]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.AWS_ECR_REPO_URL }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
            context: .
            push: true
            build-args: |
             "DATABASE_URL=${{ secrets.DATABASE_URL }}"
             "PRIVATE_KEY=${{ secrets.SESSION_SECRET_KEY }}"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: test2
          environment_name: Test2-env
          version_label: 12345
          region: us-east-2
